# Generated by Django 6.0.6 on 2026-07-09 18:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='Account number must be 9 to 18 digits.', regex='^\\d{9,18}$')])),
                ('ifsc', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code, e.g. HDFC0001234.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('payout_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('pan', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN, e.g. ABCDE1234F.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payout details',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('LIVE', 'Live'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('short_description', models.CharField(blank=True, default='', max_length=300)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('partner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('address_line', models.CharField(blank=True, default='', max_length=300)),
                ('locality', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('maps_link', models.URLField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, choices=[('PRIVATE_HALL', 'Private Hall'), ('PRIVATE_THEATRE', 'Private Theatre'), ('OPEN_THEATRE', 'Open Theatre'), ('RESORT', 'Resort'), ('PLAYZONE', 'Playzone')], max_length=20, null=True)),
                ('parking', models.BooleanField(default=False)),
                ('dining', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('occasions', models.JSONField(blank=True, default=list)),
                ('full_description', models.TextField(blank=True, default='')),
                ('site_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_person_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_person_max', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('max_persons', models.PositiveIntegerField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='SportPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('BOX_CRICKET', 'Box Cricket'), ('BADMINTON', 'Badminton'), ('VOLLEYBALL', 'Volleyball'), ('BASKETBALL', 'Basketball'), ('SWIMMING_POOL', 'Swimming Pool'), ('PICKLEBALL', 'Pickleball'), ('FOOTBALL', 'Football')], max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity_type', models.CharField(choices=[('UNLIMITED', 'Unlimited'), ('LIMITED', 'Limited')], default='UNLIMITED', max_length=10)),
                ('max_persons', models.PositiveIntegerField(blank=True, null=True)),
                ('pitches', models.PositiveIntegerField(default=1)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('details', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hrs', models.PositiveIntegerField(blank=True, null=True)),
                ('max_persons', models.PositiveIntegerField(blank=True, null=True)),
                ('charge_per_hour', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_based', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='VenuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('type', models.CharField(choices=[('VENUE', 'Venue'), ('SERVICE', 'Service')], default='VENUE', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='venues.venue')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['vendor'], name='venues_venu_vendor__370e40_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['status'], name='venues_venu_status_d850d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='sportpricing',
            constraint=models.UniqueConstraint(fields=('venue', 'sport'), name='unique_venue_sport'),
        ),
    ]
