# Generated by Django 6.0.6 on 2026-07-17 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venuedraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('record', models.JSONField(default=dict)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('locality', models.CharField(blank=True, default='', max_length=120)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('live', 'Live'), ('pending', 'Pending')], default='live', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='venues_list_status_a6f88e_idx'), models.Index(fields=['category'], name='venues_list_categor_22d4e8_idx'), models.Index(fields=['locality'], name='venues_list_localit_0ed0b4_idx'), models.Index(fields=['pincode'], name='venues_list_pincode_948d90_idx')],
            },
        ),
    ]
