# Generated by Django 6.0.6 on 2026-07-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venuedraft',
            name='review_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='venuedraft',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venuedraft',
            name='review_status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='venuedraft',
            name='review_timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('pending', 'Pending'), ('paused', 'Paused')], default='live', max_length=10),
        ),
    ]
