# Generated by Django 6.0.6 on 2026-07-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_listing_featured_venuedraft_review_checks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='review_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='listing',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='review_timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('pending', 'Pending'), ('paused', 'Paused'), ('changes', 'Changes'), ('rejected', 'Rejected')], default='live', max_length=10),
        ),
    ]
