# Generated by Django 6.0.6 on 2026-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('pending', 'Pending'), ('paused', 'Paused'), ('changes', 'Changes'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='live', max_length=10),
        ),
    ]
