# Generated by Django 6.0.6 on 2026-08-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_listing_deleted_at_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
