# Generated by Django 6.0.6 on 2026-07-30 17:48

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, default='', max_length=50)),
                ('admin', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(blank=True, default='', max_length=150)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('change', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=150)),
                ('period', models.CharField(blank=True, default='', max_length=50)),
                ('gross', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(default='', max_length=200)),
                ('reviewer', models.CharField(default='', max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField(blank=True, default='')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('flagged', 'Flagged'), ('kept', 'Kept'), ('removed', 'Removed')], default='flagged', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_fee', models.PositiveIntegerField(default=20)),
                ('fee_date', models.CharField(blank=True, default='', max_length=20)),
                ('commission', models.CharField(default='10', max_length=10)),
                ('categories', models.JSONField(blank=True, default=adminpanel.models._default_categories)),
                ('cities', models.JSONField(blank=True, default=list)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('banners', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
