# Generated by Django 6.0.6 on 2026-07-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('USER', 'User'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], max_length=10),
        ),
    ]
