# Generated by Django 6.0.6 on 2026-07-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_phoneotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
