# Generated by Django 6.0.6 on 2026-07-17 12:02

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0003_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=bookings.models.make_booking_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=250)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('date', models.DateField()),
                ('slots', models.JSONField(default=list)),
                ('per_slot', models.PositiveIntegerField(default=0)),
                ('addons', models.JSONField(default=list)),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('online', 'Online'), ('walk-in', 'Walk-in')], default='online', max_length=10)),
                ('walk_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'date'], name='bookings_bo_listing_6fa409_idx'), models.Index(fields=['user', 'date'], name='bookings_bo_user_id_4a9385_idx')],
            },
        ),
    ]
