# Generated by Django 6.0.6 on 2026-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sport',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit_label',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
