# Generated by Django 6.0.6 on 2026-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_discount_amount_booking_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fee',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
