# Generated by Django 6.0.6 on 2026-08-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_walkin_fee_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='method',
            field=models.CharField(choices=[('online', 'Online'), ('venue', 'Pay at venue'), ('walk-in', 'Walk-in')], default='online', max_length=10),
        ),
    ]
