# Generated by Django 6.0.6 on 2026-08-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='method',
            field=models.CharField(choices=[('online', 'Online'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Netbanking'), ('venue', 'Pay at venue'), ('walk-in', 'Walk-in')], default='online', max_length=10),
        ),
    ]
