# Generated by Django 6.0.6 on 2026-08-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
