# Generated by Django 6.0.6 on 2026-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_collected_booking_collected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
