# Generated by Django 6.0.6 on 2026-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_confirmation_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='occasion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='booking',
            name='occasion_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
