# Generated by Django 6.0.6 on 2026-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_occasion_booking_occasion_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='at_venue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='part_payment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pay_now',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
