"""
Django settings for BookMyVenue project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from the .env file (in the project root) into the
# environment, so os.environ can read them below.
load_dotenv(BASE_DIR / '.env')


# ---------------------------------------------------------------
# Core settings — all secrets/config come from .env, never hardcoded
# ---------------------------------------------------------------

# Use our custom User (accounts/models.py) instead of Django's default.
# MUST be set before the very first migration — never change afterwards.
AUTH_USER_MODEL = 'accounts.User'

# Crash immediately at startup if SECRET_KEY is missing — better than
# silently running with an insecure default.
SECRET_KEY = os.environ['SECRET_KEY']

# Env vars are always strings, so "True"/"False" text -> Python bool.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# "localhost,127.0.0.1" -> ['localhost', '127.0.0.1']
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Our apps
    'accounts',
    'venues',
    'bookings',
    'adminpanel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves static files (admin CSS/JS) efficiently in production.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CORS must come before CommonMiddleware to add its headers correctly.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BookMyVenue.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BookMyVenue.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# dj_database_url reads DATABASE_URL from the environment.
# - Locally: DATABASE_URL is empty -> falls back to sqlite file below.
# - Production: DATABASE_URL points at Supabase Postgres.

# "or" handles both cases: variable missing AND variable set but empty.
DATABASE_URL = os.environ.get('DATABASE_URL') or f'sqlite:///{BASE_DIR / "db.sqlite3"}'

DATABASES = {
    'default': dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,  # reuse DB connections for 10 min (faster than reconnecting per request)
    )
}

# Supabase's transaction pooler (port 6543) doesn't support server-side
# cursors — Django must be told not to use them.
if DATABASE_URL.startswith('postgres'):
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True


# ---------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------

REST_FRAMEWORK = {
    # How DRF identifies the user on each request:
    # it reads the "Authorization: Bearer <token>" header and verifies the JWT.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Frontend contract: every error body is {"message": "..."} —
    # this converts DRF's default {"detail": "..."} shape.
    'EXCEPTION_HANDLER': 'accounts.exceptions.api_exception_handler',
    # Rate limits (per IP for anonymous requests). Views opt in with
    # throttle_scope — we use scope "auth" on login/register to block
    # password brute-forcing and mass account creation.
    'DEFAULT_THROTTLE_RATES': {
        'auth': '10/min',
        # Public, unauthenticated and expensive: free-text venue search, the
        # deliberately-uncached availability endpoint, and the maps resolver
        # (which makes a blocking outbound request per uncached URL).
        'public': '60/min',
        'maps': '20/min',
        # Payment order/verify: each order call creates a real gateway order
        # and a 30-min slot hold — throttled against hold-griefing.
        'payments': '20/min',
    },
}

# JWT token lifetimes. Access token lives 30 days so users stay logged
# in for weeks (OTP-only consumer app — no passwords to steal; a lost
# phone's token still expires within 30 days).
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

# OTP SMS delivery. Fast2SMS is used when its key is present, otherwise
# 2Factor. With neither set, the OTP endpoints return an error — we never
# print codes to the console.
FAST2SMS_API_KEY = os.environ.get('FAST2SMS_API_KEY', '')
# 'q' (quick) works on any recharged account; 'otp' is Fast2SMS's dedicated
# OTP route and needs website verification on their dashboard first.
FAST2SMS_ROUTE = os.environ.get('FAST2SMS_ROUTE', 'q')
# DLT route (the cheap, TRAI-compliant one). Both must be set to use it:
#   FAST2SMS_SENDER_ID       your approved 6-character header, e.g. TBMYVN
#   FAST2SMS_DLT_TEMPLATE_ID the numeric Message ID Fast2SMS shows for the
#                            approved template in DLT Manager
# The template text is fixed at approval time; we only supply the variable.
FAST2SMS_SENDER_ID = os.environ.get('FAST2SMS_SENDER_ID', '')
FAST2SMS_DLT_TEMPLATE_ID = os.environ.get('FAST2SMS_DLT_TEMPLATE_ID', '')

TWOFACTOR_API_KEY = os.environ.get('TWOFACTOR_API_KEY', '')
# SMS template name — forces SMS delivery (omitting it can trigger
# a voice call on some accounts).
TWOFACTOR_SMS_TEMPLATE = os.environ.get('TWOFACTOR_SMS_TEMPLATE', 'OTP1')

# Resend (transactional email). Used to deliver the OTP by email ALONGSIDE
# the SMS — same code, two channels. Unset means email delivery is simply
# skipped, so nothing breaks if the key is missing.
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
# Must be a domain verified in Resend; onboarding@resend.dev works for testing.
RESEND_FROM = os.environ.get('RESEND_FROM', 'onboarding@resend.dev')
# Optional: absolute https URL of a logo image (PNG, ~240px wide, transparent).
# Unset -> the emails fall back to a typographic wordmark, which always renders
# even when the client blocks images.
BRAND_LOGO_URL = os.environ.get('BRAND_LOGO_URL', '')
BRAND_SITE_URL = os.environ.get('BRAND_SITE_URL', 'https://thebookmyvenues.in')


# Booking notifications go by EMAIL only.
#
# SMS is off because the DLT route accepts nothing but pre-approved template
# text, and the only approved template is the OTP one — a booking SMS would be
# rejected by the carrier, not merely expensive. Register booking templates
# with DLT and set NOTIFY_SMS_ENABLED=True to turn this on; the code already
# handles both channels.
#
# NOTE: this flag does NOT affect the OTP, which always goes by SMS.
NOTIFY_EMAIL_ENABLED = os.environ.get('NOTIFY_EMAIL_ENABLED', 'True') == 'True'
NOTIFY_SMS_ENABLED = os.environ.get('NOTIFY_SMS_ENABLED', 'False') == 'True'


# Razorpay (payments). Test keys and live keys are a pure env-var swap.
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')

# Supabase Storage (venue photo uploads).
SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_SERVICE_KEY = os.environ.get('SUPABASE_SERVICE_KEY', '')
SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', 'venue-photos')


# ---------------------------------------------------------------
# Logging — print our app's log messages (e.g. admin notifications)
# to the console, alongside Django's own logs.
# ---------------------------------------------------------------

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        # Everything from our own apps at INFO level and above.
        'venues': {'handlers': ['console'], 'level': 'INFO'},
        'accounts': {'handlers': ['console'], 'level': 'INFO'},
    },
}


# ---------------------------------------------------------------
# CORS — which websites' JavaScript may call this API
# ---------------------------------------------------------------

# Development convenience: allow every origin.
# In production set CORS_ALLOW_ALL_ORIGINS=False and list real
# frontend URLs in CORS_ALLOWED_ORIGINS instead.
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]

# The admin panel authenticates with a cookie session, so the browser must be
# allowed to send credentials cross-origin. With credentials on, corsheaders
# echoes the request's Origin instead of "*", so cookie login works even while
# CORS_ALLOW_ALL_ORIGINS=True. When tightening later, list the admin panel's
# exact origin in CORS_ALLOWED_ORIGINS.
CORS_ALLOW_CREDENTIALS = True

if not DEBUG and CORS_ALLOW_ALL_ORIGINS:
    # HARD FAIL, not a warning. Admin writes are CSRF-exempt and authenticate
    # with a SameSite=None cookie, so the CORS allowlist is the ONLY thing
    # standing between a logged-in admin and any website that wants to issue
    # refunds or change the platform fee on their behalf. A log line nobody
    # reads is not an acceptable guard for that; refusing to boot is.
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'CORS_ALLOW_ALL_ORIGINS=True in production while admin sessions use '
        'credentialed cookies — any website could drive the admin API with a '
        'logged-in admin\'s session. Set CORS_ALLOW_ALL_ORIGINS=False and '
        'list the real frontend origins in CORS_ALLOWED_ORIGINS.'
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Where collectstatic gathers files in production (admin CSS/JS);
# WhiteNoise serves them from here.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# ---------------------------------------------------------------
# Production security (active only when DEBUG=False, i.e. on Render)
# ---------------------------------------------------------------

if not DEBUG:
    # Render terminates HTTPS at its proxy; this header tells Django
    # the original request was secure.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    # Browsers remember to ALWAYS use HTTPS for this domain (1 year).
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # The admin panel is served from a different site, so its session cookie
    # must be sent cross-site. SameSite=None requires Secure (set above).
    SESSION_COOKIE_SAMESITE = 'None'
